{
    "impact": {
        "cvss": [
            [
                {
                    "vectorString": "4.2/CVSS:3.0/AV:P/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H", 
                    "version": "3.0"
                }
            ]
        ]
    }, 
    "description": {
        "description_data": [
            {
                "lang": "eng", 
                "value": "A flaw was found in the Linux kernel's ext4 filesystem. A local user can cause a use-after-free in ext4_xattr_set_entry function and a denial of service or unspecified other impact may occur by renaming a file in a crafted ext4 filesystem image."
            }
        ]
    }, 
    "data_type": "CVE", 
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "n/a"
                                        }
                                    ]
                                }, 
                                "product_name": "kernel"
                            }
                        ]
                    }, 
                    "vendor_name": "[UNKNOWN]"
                }
            ]
        }
    }, 
    "data_format": "MITRE", 
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng", 
                        "value": "CWE-416"
                    }
                ]
            }
        ]
    }, 
    "data_version": "4.0", 
    "references": {
        "reference_data": [
            {
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10879", 
                "refsource": "CONFIRM", 
                "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10879"
            }
        ]
    }, 
    "CVE_data_meta": {
        "ID": "CVE-2018-10879", 
        "ASSIGNER": "lpardo@redhat.com"
    }
}