{
   "CVE_data_meta" : {
      "ASSIGNER" : "lpardo@redhat.com",
      "ID" : "CVE-2018-10881",
      "STATE" : "PUBLIC"
   },
   "affects" : {
      "vendor" : {
         "vendor_data" : [
            {
               "product" : {
                  "product_data" : [
                     {
                        "product_name" : "kernel",
                        "version" : {
                           "version_data" : [
                              {
                                 "version_value" : "n/a"
                              }
                           ]
                        }
                     }
                  ]
               },
               "vendor_name" : "[UNKNOWN]"
            }
         ]
      }
   },
   "data_format" : "MITRE",
   "data_type" : "CVE",
   "data_version" : "4.0",
   "description" : {
      "description_data" : [
         {
            "lang" : "eng",
            "value" : "A flaw was found in the Linux kernel's ext4 filesystem. A local user can cause an out-of-bound access in ext4_get_group_info function, a denial of service, and a system crash by mounting and operating on a crafted ext4 filesystem image."
         }
      ]
   },
   "impact" : {
      "cvss" : [
         [
            {
               "vectorString" : "4.2/CVSS:3.0/AV:P/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
               "version" : "3.0"
            }
         ]
      ]
   },
   "problemtype" : {
      "problemtype_data" : [
         {
            "description" : [
               {
                  "lang" : "eng",
                  "value" : "CWE-787"
               }
            ]
         }
      ]
   },
   "references" : {
      "reference_data" : [
         {
            "name" : "http://patchwork.ozlabs.org/patch/929792/",
            "refsource" : "CONFIRM",
            "url" : "http://patchwork.ozlabs.org/patch/929792/"
         },
         {
            "name" : "https://bugzilla.kernel.org/show_bug.cgi?id=200015",
            "refsource" : "CONFIRM",
            "url" : "https://bugzilla.kernel.org/show_bug.cgi?id=200015"
         },
         {
            "name" : "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10881",
            "refsource" : "CONFIRM",
            "url" : "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10881"
         },
         {
            "name" : "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6e8ab72a812396996035a37e5ca4b3b99b5d214b",
            "refsource" : "CONFIRM",
            "url" : "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6e8ab72a812396996035a37e5ca4b3b99b5d214b"
         }
      ]
   }
}
