{
    "impact": {
        "cvss": [
            [
                {
                    "vectorString": "5.9/CVSS:3.0/AV:L/AC:L/PR:L/UI:R/S:C/C:H/I:N/A:N",
                    "version": "3.0"
                }
            ]
        ]
    },
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "python-oslo-middleware before versions 3.8.1, 3.19.1, 3.23.1 is vulnerable to an information disclosure. Software using the CatchError class could include sensitive values in a traceback's error message. System users could exploit this flaw to obtain sensitive information from OpenStack component error logs (for example, keystone tokens)."
            }
        ]
    },
    "data_type": "CVE",
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "python-oslo-middleware 3.8.1"
                                        },
                                        {
                                            "version_value": " python-oslo-middleware 3.19.1"
                                        },
                                        {
                                            "version_value": " python-oslo-middleware 3.23.1"
                                        }
                                    ]
                                },
                                "product_name": "python-oslo-middleware"
                            }
                        ]
                    },
                    "vendor_name": ""
                }
            ]
        }
    },
    "data_format": "MITRE",
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "CWE-532"
                    }
                ]
            }
        ]
    },
    "data_version": "4.0",
    "references": {
        "reference_data": [
            {
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2017-2592"
            }
        ]
    },
    "CVE_data_meta": {
        "ID": "CVE-2017-2592",
        "ASSIGNER": "lpardo@redhat.com"
    }
}
