{
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
        "ID": "CVE-2018-1060",
        "ASSIGNER": "sfowler@redhat.com"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "vendor_name": "[UNKNOWN]",
                    "product": {
                        "product_data": [
                            {
                                "product_name": "python",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "python 2.7.15"
                                        },
                                        {
                                            "version_value": "python 3.4.9"
                                        },
                                        {
                                            "version_value": "python 3.5.6"
                                        },
                                        {
                                            "version_value": "python 3.7.0"
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                }
            ]
        }
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "CWE-20"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-1060"
            }
        ]
    },
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "python before versions 2.7.15, 3.4.9, 3.5.6 and 3.7.0 is vulnerable to catastrophic backtracking in pop3lib's apop() method. An attacker could use this flaw to cause denial of service."
            }
        ]
    },
    "impact": {
        "cvss": [
            [
                {
                    "vectorString": "4.3/CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:L",
                    "version": "3.0"
                }
            ]
        ]
    }
}
