{
    "CVE_data_meta": {
        "ASSIGNER": "cve@mitre.org",
        "ID": "CVE-2019-19950",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "product_name": "n/a",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "n/a"
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "vendor_name": "n/a"
                }
            ]
        }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "In GraphicsMagick 1.4 snapshot-20190403 Q8, there is a use-after-free in ThrowException and ThrowLoggedException of magick/error.c."
            }
        ]
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "n/a"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "url": "https://sourceforge.net/p/graphicsmagick/bugs/603/",
                "refsource": "MISC",
                "name": "https://sourceforge.net/p/graphicsmagick/bugs/603/"
            },
            {
                "url": "http://hg.graphicsmagick.org/hg/GraphicsMagick/rev/44ab7f6c20b4",
                "refsource": "MISC",
                "name": "http://hg.graphicsmagick.org/hg/GraphicsMagick/rev/44ab7f6c20b4"
            },
            {
                "refsource": "SUSE",
                "name": "openSUSE-SU-2020:0055",
                "url": "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00026.html"
            }
        ]
    }
}