{
    "CVE_data_meta": {
        "ASSIGNER": "cve@mitre.org",
        "ID": "CVE-2019-19844",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "product_name": "n/a",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "n/a"
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "vendor_name": "n/a"
                }
            ]
        }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "Django before 1.11.27, 2.x before 2.2.9, and 3.x before 3.0.1 allows account takeover. A suitably crafted email address (that is equal to an existing user's email address after case transformation of Unicode characters) would allow an attacker to be sent a password reset token for the matched user account. (One mitigation in the new releases is to send password reset tokens only to the registered user email address.)"
            }
        ]
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "n/a"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "url": "https://docs.djangoproject.com/en/dev/releases/security/",
                "refsource": "MISC",
                "name": "https://docs.djangoproject.com/en/dev/releases/security/"
            },
            {
                "refsource": "MISC",
                "name": "https://groups.google.com/forum/#!topic/django-announce/3oaB2rVH3a0",
                "url": "https://groups.google.com/forum/#!topic/django-announce/3oaB2rVH3a0"
            },
            {
                "refsource": "CONFIRM",
                "name": "https://www.djangoproject.com/weblog/2019/dec/18/security-releases/",
                "url": "https://www.djangoproject.com/weblog/2019/dec/18/security-releases/"
            },
            {
                "refsource": "UBUNTU",
                "name": "USN-4224-1",
                "url": "https://usn.ubuntu.com/4224-1/"
            },
            {
                "refsource": "DEBIAN",
                "name": "DSA-4598",
                "url": "https://www.debian.org/security/2020/dsa-4598"
            },
            {
                "refsource": "BUGTRAQ",
                "name": "20200108 [SECURITY] [DSA 4598-1] python-django security update",
                "url": "https://seclists.org/bugtraq/2020/Jan/9"
            }
        ]
    }
}