{
   "CVE_data_meta" : {
      "ASSIGNER" : "cve@mitre.org",
      "ID" : "CVE-2012-1502",
      "STATE" : "PUBLIC"
   },
   "affects" : {
      "vendor" : {
         "vendor_data" : [
            {
               "product" : {
                  "product_data" : [
                     {
                        "product_name" : "n/a",
                        "version" : {
                           "version_data" : [
                              {
                                 "version_value" : "n/a"
                              }
                           ]
                        }
                     }
                  ]
               },
               "vendor_name" : "n/a"
            }
         ]
      }
   },
   "data_format" : "MITRE",
   "data_type" : "CVE",
   "data_version" : "4.0",
   "description" : {
      "description_data" : [
         {
            "lang" : "eng",
            "value" : "Double free vulnerability in the PyPAM_conv in PAMmodule.c in PyPam 0.5.0 and earlier allows remote attackers to cause a denial of service (application crash) or possibly execute arbitrary code via a NULL byte in a password string."
         }
      ]
   },
   "problemtype" : {
      "problemtype_data" : [
         {
            "description" : [
               {
                  "lang" : "eng",
                  "value" : "n/a"
               }
            ]
         }
      ]
   },
   "references" : {
      "reference_data" : [
         {
            "url" : "http://www.lsexperts.de/advisories/lse-2012-03-01.txt"
         },
         {
            "url" : "http://www.debian.org/security/2012/dsa-2430"
         },
         {
            "url" : "https://security.gentoo.org/glsa/201507-09"
         },
         {
            "url" : "http://lists.opensuse.org/opensuse-updates/2012-04/msg00027.html"
         },
         {
            "url" : "http://ubuntu.com/usn/usn-1395-1"
         },
         {
            "url" : "http://www.osvdb.org/79892"
         },
         {
            "url" : "http://secunia.com/advisories/48312"
         },
         {
            "url" : "http://secunia.com/advisories/48332"
         },
         {
            "url" : "http://secunia.com/advisories/48746"
         },
         {
            "url" : "https://exchange.xforce.ibmcloud.com/vulnerabilities/73857"
         }
      ]
   }
}
