{
   "CVE_data_meta" : {
      "ASSIGNER" : "cve@mitre.org",
      "ID" : "CVE-2011-4944",
      "STATE" : "PUBLIC"
   },
   "affects" : {
      "vendor" : {
         "vendor_data" : [
            {
               "product" : {
                  "product_data" : [
                     {
                        "product_name" : "n/a",
                        "version" : {
                           "version_data" : [
                              {
                                 "version_value" : "n/a"
                              }
                           ]
                        }
                     }
                  ]
               },
               "vendor_name" : "n/a"
            }
         ]
      }
   },
   "data_format" : "MITRE",
   "data_type" : "CVE",
   "data_version" : "4.0",
   "description" : {
      "description_data" : [
         {
            "lang" : "eng",
            "value" : "Python 2.6 through 3.2 creates ~/.pypirc with world-readable permissions before changing them after data has been written, which introduces a race condition that allows local users to obtain a username and password by reading this file."
         }
      ]
   },
   "problemtype" : {
      "problemtype_data" : [
         {
            "description" : [
               {
                  "lang" : "eng",
                  "value" : "n/a"
               }
            ]
         }
      ]
   },
   "references" : {
      "reference_data" : [
         {
            "url" : "http://www.openwall.com/lists/oss-security/2012/03/27/2"
         },
         {
            "url" : "http://www.openwall.com/lists/oss-security/2012/03/27/5"
         },
         {
            "url" : "http://www.openwall.com/lists/oss-security/2012/03/27/10"
         },
         {
            "url" : "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=650555"
         },
         {
            "url" : "https://bugzilla.redhat.com/show_bug.cgi?id=758905"
         },
         {
            "url" : "http://bugs.python.org/file23824/pypirc-secure.diff"
         },
         {
            "url" : "http://bugs.python.org/issue13512"
         },
         {
            "url" : "http://lists.apple.com/archives/security-announce/2013/Oct/msg00004.html"
         },
         {
            "url" : "http://www.ubuntu.com/usn/USN-1596-1"
         },
         {
            "url" : "http://www.ubuntu.com/usn/USN-1613-2"
         },
         {
            "url" : "http://www.ubuntu.com/usn/USN-1592-1"
         },
         {
            "url" : "http://www.ubuntu.com/usn/USN-1613-1"
         },
         {
            "url" : "http://www.ubuntu.com/usn/USN-1615-1"
         },
         {
            "url" : "http://www.ubuntu.com/usn/USN-1616-1"
         },
         {
            "url" : "http://secunia.com/advisories/51089"
         },
         {
            "url" : "http://secunia.com/advisories/50858"
         },
         {
            "url" : "http://secunia.com/advisories/51024"
         },
         {
            "url" : "http://secunia.com/advisories/51040"
         },
         {
            "url" : "http://secunia.com/advisories/51087"
         }
      ]
   }
}
